sudo: required
dist: trusty
language: c
cache:
    directories:
        - deps

os:
  - linux

install:
  - . .travis/install_saw.sh

script:
  - cp -n /AES_GCM_SIV_128/AES_GCM_SIV_128_Performance_Code/* asm/verif-src
  - make -C asm/verif-src
  - Proof