sudo: required
dist: trusty
language: c
cache:
    directories:
        - deps

apt:
  packages:
    - clang-3.8
    - llvm-3.8


os:
  - linux

env:
  - SAWPROOF=ref-128
  - SAWPROOF=ref-256


install:
  - . .travis/install_saw.sh

script:
  - cd proof/ref-128
  - make
