sudo: required
dist: trusty
language: c
cache:
    directories:
        - deps
addons:
  apt:
    packages:
      - clang-3.8
      - llvm-3.8


os:
  - linux

env:
  - SAWPROOF=ref-128 PROOF=aes_encrypt_proof
  - SAWPROOF=ref-128 PROOF=proof
  - SAWPROOF=ref-128 PROOF=aes_emulation
  - SAWPROOF=ref-256 PROOF=aes_encrypt_proof
  - SAWPROOF=ref-256 PROOF=proof
  - SAWPROOF=ref-256 PROOF=aes_emulation



install:
  - . .travis/install_saw.sh

script:
  - cd proof/$SAWPROOF
  - travis_wait 50 make $PROOF
