sudo: required
dist: trusty
language: c
cache:
  directories:
    - .stack-work
    - saw-script/.stack-work
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - llvm-3.8
      - gcc-7

os:
  - linux

env:
  - PROOF=ref-128
  - PROOF=ref-256
  - PROOF=asm

before_install:
  - git submodule update --init
  - cd saw-script; git submodule update --init
  - cd saw-script/deps/abcBridge; git submodule update --init

install:
  - wget -qO- https://get.haskellstack.org/ | sh
  - curl --retry 3 https://s3-us-west-2.amazonaws.com/s2n-public-test-dependencies/z3-2017-04-04-Ubuntu14.04-64 --output bin/z3; chmod +x bin/z3
  - curl --retry 3 https://s3-us-west-2.amazonaws.com/s2n-public-test-dependencies/yices_smt2-linux-static-2017-06-21 --output bin/yices-smt2; chmod +x bin/yices-smt2
  - stack install saw-script --local-bin-path bin
  - stack build dasm

script:
  - make -C proof/$PROOF
