sudo: required
dist: trusty
language: c

git:
  submodules: false

cache:
    directories:
        - deps

addons:
  apt:
    sources:
      sourceline: 'ppa:jonathonf/gcc-7.1'
    packages:
      - gcc-7

os:
  - linux


before_install:
  - git submodule update --init

install:
  - . .travis/install_saw.sh

script:
  - cp -n AES-GCM-SIV/AES_GCM_SIV_128/AES_GCM_SIV_128_Performance_Code/* asm/verif-src
  - make -C asm/verif-src
  - Proof