CLANG=clang-4.0

FILES=main.c GCM_SIV_c.c clmul_emulator.c aes_emulation.c aes_emulation_tables.c

%.bc: %.c
	$(CLANG) -c -emit-llvm -o $@ $^

.PHONY: proof clean

proof: clmul_emulator.bc
	



clean:
	-rm *.bc



# 	$(GCC) $(FLAGS) $(DEF) main.c GCM_SIV_c.c clmul_emulator.c aes_emulation.c aes_emulation_tables.c -o GCM_SIV_GENERAL_V02_BE
# 	$(GCC) $(FLAGS) $(DEF) main.c GCM_SIV_c.c clmul_emulator.c aes_emulation.c aes_emulation_tables.c -DLE -o GCM_SIV_GENERAL_V02_LE
# 

