name:                aes-gcm-siv-performance-proof
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- bytestring
- saw-script
- saw-core
- parameterized-utils
- containers
- macaw-symbolic
- macaw-x86
- macaw-x86-symbolic
- crucible
- crucible-llvm
- flexdis86
- crucible-saw
- cryptol-verifier
- abcBridge
- ansi-terminal

executables:
  proof:
    main: Proof.hs
    source-dirs: src
