flags: {}
packages:
  - .
  - deps/saw-script
  - deps/saw-script/deps/flexdis86
  - deps/saw-script/deps/parameterized-utils
  - deps/saw-script/deps/macaw/base
  - deps/saw-script/deps/macaw/x86
  - deps/saw-script/deps/macaw/symbolic
  - deps/saw-script/deps/macaw/x86_symbolic
  - deps/saw-script/deps/elf-edit
  - deps/saw-script/deps/dwarf
  - deps/saw-script/deps/crucible/crucible
  - deps/saw-script/deps/crucible/crucible-llvm
  - deps/saw-script/deps/crucible/crucible-saw
  - deps/saw-script/deps/crucible/galois-matlab
  - deps/saw-script/deps/llvm-pretty
  - deps/saw-script/deps/saw-core
  - deps/saw-script/deps/saw-core-aig
  - deps/saw-script/deps/saw-core-sbv
  - deps/saw-script/deps/abcBridge
  - deps/saw-script/deps/cryptol-verifier
  - deps/saw-script/deps/cryptol
  - deps/saw-script/deps/llvm-verifier
  - deps/saw-script/deps/jvm-verifier
  - deps/saw-script/deps/jvm-parser
  - deps/saw-script/deps/llvm-pretty-bc-parser
extra-deps:
  - IfElse-0.85
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - monad-supply-0.6
  - simple-smt-0.7.1
  - GraphSCC-1.0.4
  - monadLib-3.7.3
  - presburger-1.3.1
  - smtLib-1.0.8
  - sbv-7.6
  - tasty-hunit-0.10.0.1
  - aig-0.2.6@sha256:b7f97a6e4ee26416d9b7e88f9e74e1bb2cf1591b290bef383cf04ff9ab95260e,1567
resolver: lts-10.6

nix:
  enable: true
  pure: false
  packages:
  - z3
  - zlib
  - wget
  - unzip
